# Netlify設定ファイル
[build]
  publish = "."
  command = ""
  functions = "netlify/functions"

[[redirects]]
  from = "/analysis"
  to = "/analysis.html"
  status = 200

[[redirects]]
  from = "/learning"
  to = "/learning.html"
  status = 200

[[redirects]]
  from = "/stats"
  to = "/stats.html"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

[build.environment]
  NODE_VERSION = "18"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"