# Netlify設定ファイル
[build]
  publish = "."
  command = ""
  functions = "netlify/functions"

[functions]
  # Increase timeout for AI API calls
  "improve-text" = { timeout = "30s" }
  "analyze-text" = { timeout = "30s" }

[[redirects]]
  from = "/analysis"
  to = "/analysis.html"
  status = 200

[[redirects]]
  from = "/learning"
  to = "/learning.html"
  status = 200

[[redirects]]
  from = "/stats"
  to = "/stats.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Headers for sitemap.xml
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "text/xml"

# Headers for robots.txt  
[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Exclude important files from SPA redirect
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

[[redirects]]
  from = "/robots.txt"  
  to = "/robots.txt"
  status = 200

# SPA fallback for other paths
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200